<template>
  <a-card class="containers-container">
    <template #title>
      <div class="card-header">
        <span class="title">{{ t('containerHost') }}</span>
        <div class="header-actions">
          <a-button type="outline" @click="openCreateDrawer">{{ t('create') }}</a-button>
        </div>
      </div>
    </template>

    <!-- 节点列表表格 -->
    <a-table 
      :columns="columns" 
      :data="containerNodes" 
      :loading="loading" 
      :pagination="pagination"
      @page-change="handlePageChange"
      @page-size-change="handlePageSizeChange"
      :scroll="scroll"
      row-key="id"
    >
      <template #endpoint_type="{ record }">
        <a-tag :color="record.endpoint_type === 'unix_socket' ? 'blue' : 'green'">
          {{ record.endpoint_type === 'unix_socket' ? t('unixSocket') : t('tcp') }}
        </a-tag>
      </template>

      <template #status="{ record }">
        <a-tag :color="getStatusColor(record.status)">
          {{ getStatusText(record.status) }}
        </a-tag>
      </template>
      <template #created_at="{ record }">
        {{ formatDate(record.created_at) }}
      </template>
      <template #operation="{ record }">
        <a-button type="text" size="small" @click="openEditDrawer(record)">{{ t('edit') }}</a-button>
        <a-dropdown>
          <a-button type="text" size="small">
            {{ t('more') }}
            <icon-down />
          </a-button>
          <template #content>
            <a-doption 
              @click="showDeleteModal(record)"
              :disabled="record.identifier === 'localhost'"
              :tooltip="record.identifier === 'localhost' ? t('cannotDeleteLocalhostNode') : ''"
            >
              <icon-delete />
              {{ t('delete') }}
            </a-doption>
          </template>
        </a-dropdown>
      </template>
    </a-table>

    <!-- 新增/编辑节点抽屉 -->
    <a-drawer
      v-model:visible="drawerVisible"
      :width="isMobile ? '90%' : 700"
      :title="isEditMode ? t('edit') : t('create')"
      placement="right"
      :destroy-on-close="true"
      :footer="true"
    >
      <a-form
        ref="nodeFormRef"
        :model="nodeForm"
        :rules="rules"
        layout="vertical"
      >
        <a-form-item field="name" :label="t('name')">
          <a-input
            v-model="nodeForm.name"
            :placeholder="t('enterNodeName')"
          />
        </a-form-item>
        <a-form-item field="description" :label="t('description')">
          <a-input
            v-model="nodeForm.description"
            :placeholder="t('enterDescription')"
          />
        </a-form-item>
        <a-form-item field="identifier" :label="t('identifier')">
          <a-input
            v-model="nodeForm.identifier"
            disabled
          />
          <div class="form-hint">
            <span class="hint-text">{{ t('identifierHint') }}</span>
          </div>
        </a-form-item>
        <a-form-item field="endpoint_type" :label="t('endpointType')">
          <a-radio-group v-model="nodeForm.endpoint_type">
            <a-radio value="unix_socket">{{ t('unixSocket') }}</a-radio>
            <a-radio value="tcp">{{ t('tcp') }}</a-radio>
          </a-radio-group>
        </a-form-item>
        <a-form-item field="endpoint_url" :label="t('endpoint')">
          <a-input-group>
            <a-input 
              :model-value="nodeForm.endpoint_type === 'unix_socket' ? 'unix://' : 'tcp://'"
              readonly
              style="width: 85px; flex: none;"
              class="endpoint-prefix"
            />
            <a-input
              v-model="endpointPath"
              :placeholder="endpointPlaceholder"
              style="flex: 1; width: 100%; min-width: 300px;"
            />
          </a-input-group>
        </a-form-item>
        
        <a-form-item field="compose_path" :label="t('composePath')">
          <a-input
            v-model="nodeForm.compose_path"
            disabled
            style="width: 100%"
          />
        </a-form-item>
        <div class="form-hint">
          <span class="hint-text">{{ t('composePathAutoGenerated') }}</span>
        </div>
        <!-- TLS配置部分 - 仅在TCP连接时显示 -->
        <a-form-item field="use_tls" label="TLS" v-if="nodeForm.endpoint_type === 'tcp'">
          <a-switch v-model="nodeForm.use_tls" />
        </a-form-item>
        <!-- TLS 证书配置 -->
        <template v-if="nodeForm.endpoint_type === 'tcp' && nodeForm.use_tls">
          <a-form-item field="tls_cert" label="cert.pem">
            <div class="cert-container">
              <a-textarea
                v-model="nodeForm.tls_cert"
                :placeholder="t('enterCertContent') + '\n例如：\n-----BEGIN CERTIFICATE-----\nMIIC...\n-----END CERTIFICATE-----'"
                :rows="6"
                :auto-size="{ minRows: 6, maxRows: 12 }"
                class="cert-textarea"
              />
              <div class="cert-actions">
                <a-button size="small" @click="() => handleFileUpload('tls_cert')">
                  <template #icon><icon-upload /></template>
                  {{ t('uploadFile') }}
                </a-button>
                <a-button size="small" @click="() => nodeForm.tls_cert = ''" v-if="nodeForm.tls_cert">
                  <template #icon><icon-delete /></template>
                  {{ t('clear') }}
                </a-button>
              </div>
            </div>
          </a-form-item>

          <a-form-item field="tls_key" label="key.pem">
            <div class="cert-container">
              <a-textarea
                v-model="nodeForm.tls_key"
                :placeholder="t('enterKeyContent') + '\n例如：\n-----BEGIN PRIVATE KEY-----\nMIIE...\n-----END PRIVATE KEY-----'"
                :rows="6"
                :auto-size="{ minRows: 6, maxRows: 12 }"
                class="cert-textarea"
              />
              <div class="cert-actions">
                <a-button size="small" @click="() => handleFileUpload('tls_key')">
                  <template #icon><icon-upload /></template>
                  {{ t('uploadFile') }}
                </a-button>
                <a-button size="small" @click="() => nodeForm.tls_key = ''" v-if="nodeForm.tls_key">
                  <template #icon><icon-delete /></template>
                  {{ t('clear') }}
                </a-button>
              </div>
            </div>
          </a-form-item>

          <a-form-item field="tls_ca_cert" label="ca.pem">
            <div class="cert-container">
              <a-textarea
                v-model="nodeForm.tls_ca_cert"
                :placeholder="t('enterCACertContent') + '\n例如：\n-----BEGIN CERTIFICATE-----\nMIIC...\n-----END CERTIFICATE-----'"
                :rows="6"
                :auto-size="{ minRows: 6, maxRows: 12 }"
                class="cert-textarea"
              />
              <div class="cert-actions">
                <a-button size="small" @click="() => handleFileUpload('tls_ca_cert')">
                  <template #icon><icon-upload /></template>
                  {{ t('uploadFile') }}
                </a-button>
                <a-button size="small" @click="() => nodeForm.tls_ca_cert = ''" v-if="nodeForm.tls_ca_cert">
                  <template #icon><icon-delete /></template>
                  {{ t('clear') }}
                </a-button>
              </div>
            </div>
          </a-form-item>
        </template>
      </a-form>
      <template #footer>
        <a-button @click="closeDrawer">{{ t('cancel') }}</a-button>
        <a-button 
          type="primary" 
          @click="handleSubmit"
          :loading="submitting"
        >
          {{ t('save') }}
        </a-button>
      </template>
    </a-drawer>

  </a-card>

    <!-- 删除确认对话框 -->
    <a-modal
      v-model:visible="deleteModalVisible"
      :title="t('confirmDeleteNode')"
      :ok-text="t('confirm')"
      :cancel-text="t('cancel')"
      @ok="confirmDelete"
      @cancel="cancelDelete"
    >
      <p>{{ t('confirmDeleteNode') }}</p>
    </a-modal>
</template>

<script setup>
import { reactive, ref, computed, onMounted, onUnmounted, watch, nextTick } from 'vue';

// 生成随机标识符的函数
const generateRandomIdentifier = () => {
  // 生成8位随机字符串，包含小写字母和数字
  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
  let result = 'node_';
  for (let i = 0; i < 8; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
};

// 标识符生成函数
const generateIdentifier = (text) => {
  // 检查是否包含中文字符
  if (/[\u4e00-\u9fa5]/.test(text)) {
    // 如果包含中文，生成随机标识符
    return generateRandomIdentifier();
  } else {
    // 不包含中文，直接使用，移除特殊字符
    return text.toLowerCase().replace(/[^a-zA-Z0-9]/g, '_');
  }
}
import { t } from '../../utils/locale';
import { 
  getContainerNodes, 
  getContainerNodeStatus, 
  createContainerNode, 
  updateContainerNode,
  deleteContainerNode
} from '../../api/container';
import { Message, Modal } from '@arco-design/web-vue';
import { IconDown, IconDelete, IconUpload } from '@arco-design/web-vue/es/icon';
// 响应式数据
const isMobile = ref(false);
// 删除确认对话框相关状态
const deleteModalVisible = ref(false);
const nodeToDelete = ref(null);

// 检测是否为移动设备
const checkIsMobile = () => {
  isMobile.value = window.innerWidth <= 768;
};

// 表格相关数据
const containerNodes = ref([]);
const loading = ref(false);
const pagination = reactive({
  current: 1,
  pageSize: 10,
  total: 0,
  showTotal: true,
  showJumper: true,
  pageSizeOptions: [10, 20, 50, 100],
  showPageSize: true
});

// 表格滚动配置
const scroll = {
  x: 1300,
  y: 400
};

// 表格列定义
const columns = computed(() => [
  {
    title: t.value('id'),
    dataIndex: 'id',
    width: 80
  },
  {
    title: t.value('name'),
    dataIndex: 'name',
    width: 150
  },
  {
    title: t.value('description'),
    dataIndex: 'description',
    width: 200
  },
  {
    title: t.value('endpointType'),
    dataIndex: 'endpoint_type',
    slotName: 'endpoint_type',
    width: 140
  },
  {
    title: t.value('endpoint'),
    dataIndex: 'endpoint_url',
    width: 300
  },
  {
    title: t.value('status'),
    dataIndex: 'status',
    slotName: 'status',
    width: 120
  },
  {
    title: t.value('createdAt'),
    dataIndex: 'created_at',
    slotName: 'created_at',
    width: 200
  },
  {
    title: t.value('action'),
    dataIndex: 'operation',
    slotName: 'operation',
    width: 200,
    fixed: 'right'
  }
]);

// 格式化日期
const formatDate = (dateString) => {
  if (!dateString) return '';
  const date = new Date(dateString);
  return date.toLocaleString();
};

// 获取状态颜色
const getStatusColor = (status) => {
  switch (status) {
    case 'online': return 'green';
    case 'offline': return 'red';
    case 'checking': return 'blue';
    case 'unknown': return 'gray';
    default: return 'gray';
  }
};

// 获取状态文本
const getStatusText = (status) => {
  switch (status) {
    case 'online': return t.value('online');
    case 'offline': return t.value('offline');
    case 'checking': return t.value('checking');
    case 'unknown': return t.value('unknown');
    default: return t.value('unknown');
  }
};

// 获取单个节点的状态（带超时控制）
const fetchNodeStatus = async (nodeId, timeout = 3000) => {
  try {
    const timeoutPromise = new Promise((_, reject) => {
      setTimeout(() => reject(new Error('timeout')), timeout);
    });
    
    const statusPromise = getContainerNodeStatus(nodeId);
    const statusResponse = await Promise.race([statusPromise, timeoutPromise]);
    
    return statusResponse.is_online ? 'online' : 'offline';
  } catch (error) {
    if (error.message === 'timeout') {
      console.warn(`节点 ${nodeId} 状态检查超时`);
    } else {
      console.error(`获取节点 ${nodeId} 状态失败:`, error);
    }
    return 'offline';
  }
};

// 获取容器节点列表
const fetchContainerNodes = async (page = 1) => {
  try {
    loading.value = true;
    const response = await getContainerNodes({
      skip: (page - 1) * pagination.pageSize,
      limit: pagination.pageSize
    });
    
    console.log('容器节点API响应:', response);
    
    // 根据实际API响应结构调整
    let nodes = [];
    let total = 0;
    
    if (response && response.items && Array.isArray(response.items)) {
      // 如果响应包含items字段
      nodes = response.items;
      total = response.total || response.items.length;
    } else if (response && Array.isArray(response)) {
      // 如果响应直接是数组
      nodes = response;
      total = response.length;
    } else {
      nodes = [];
      total = 0;
    }
    
    // 先显示节点列表，状态设为检查中
    const nodesWithPendingStatus = nodes.map(node => ({
      ...node,
      status: 'checking'
    }));
    
    containerNodes.value = nodesWithPendingStatus;
    pagination.total = total;
    loading.value = false; // 先结束加载状态
    
    // 异步获取每个节点的实时状态
    nodes.forEach(async (node, index) => {
      try {
        const status = await fetchNodeStatus(node.id);
        // 更新对应节点的状态
        if (containerNodes.value[index] && containerNodes.value[index].id === node.id) {
          containerNodes.value[index].status = status;
        }
      } catch (error) {
        console.error(`处理节点 ${node.id} 时出错:`, error);
        if (containerNodes.value[index] && containerNodes.value[index].id === node.id) {
          containerNodes.value[index].status = 'unknown';
        }
      }
    });

  } catch (error) {
    console.error('获取容器节点列表失败:', error);
    Message.error(t.value('getContainerNodesFailed'));
    containerNodes.value = [];
    pagination.total = 0;
  } finally {
    loading.value = false;
  }
};

// 处理分页变化
const handlePageChange = (page) => {
  pagination.current = page;
  fetchContainerNodes(page);
};

// 处理分页大小变化
const handlePageSizeChange = (pageSize) => {
  pagination.pageSize = pageSize;
  pagination.current = 1; // 重置到第一页
  fetchContainerNodes(1);
};

// 定时刷新节点状态
const refreshNodeStatuses = () => {
  containerNodes.value.forEach(async (node) => {
    try {
      const status = await fetchNodeStatus(node.id);
      // 更新节点状态
      node.status = status;
    } catch (error) {
      console.error(`刷新节点 ${node.id} 状态失败:`, error);
    }
  });
};

// 抽屉相关状态
const drawerVisible = ref(false);
const isEditMode = ref(false);
const submitting = ref(false);
const nodeFormRef = ref(null);
const editingNodeId = ref(null);

// 表单数据
const nodeForm = reactive({
  name: '',
  description: '',
  identifier: '',
  endpoint_type: 'unix_socket',
  endpoint_url: 'unix:///var/run/docker.sock',
  compose_path: '',
  use_tls: false,
  tls_cert: '',
  tls_key: '',
  tls_ca_cert: ''
});

// 端点路径（不包含协议前缀）
const endpointPath = ref('/var/run/docker.sock');

// 标志：是否正在编辑模式下设置数据
const isSettingEditData = ref(false);

// 计算属性：端点前缀

// 计算属性：占位符文本
const endpointPlaceholder = computed(() => {
  return nodeForm.endpoint_type === 'unix_socket' 
    ? t.value('unixSocketPlaceholder') 
    : t.value('tcpPlaceholder');
});

// 监听节点名称变化，自动更新identifier
watch(() => nodeForm.name, (newName) => {
  // 只有在非编辑模式或者编辑的不是localhost节点时才自动更新
  if (!isEditMode.value || (isEditMode.value && nodeForm.identifier !== 'localhost')) {
    if (newName) {
      // 检查是否包含中文字符
      if (/[\u4e00-\u9fa5]/.test(newName)) {
        // 包含中文，生成随机标识符
        nodeForm.identifier = generateIdentifier(newName);
      } else {
        // 不包含中文，直接使用，移除特殊字符
        nodeForm.identifier = newName.toLowerCase().replace(/[^a-zA-Z0-9]/g, '_');
      }
    } else {
      nodeForm.identifier = '';
    }
  }
});

// 监听identifier变化，自动更新compose_path
watch(() => nodeForm.identifier, (newIdentifier) => {
  if (newIdentifier) {
    nodeForm.compose_path = `/opt/blackpotbpanel-v2/server/composeapp/compose-${newIdentifier}`;
  } else {
    nodeForm.compose_path = '';
  }
});

// 监听连接类型变化，自动切换默认路径
watch(() => nodeForm.endpoint_type, (newType) => {
  // 如果正在设置编辑数据，跳过自动切换
  if (isSettingEditData.value) {
    return;
  }
  
  if (newType === 'unix_socket') {
    endpointPath.value = '/var/run/docker.sock';
    // Unix Socket 不需要 TLS，重置 TLS 配置
    nodeForm.use_tls = false;
    nodeForm.tls_cert = '';
    nodeForm.tls_key = '';
    nodeForm.tls_ca_cert = '';
  } else if (newType === 'tcp') {
    endpointPath.value = '';
  }
  updateEndpointUrl();
});

// 监听端点路径变化，更新完整URL
watch(endpointPath, () => {
  // 如果正在设置编辑数据，跳过自动更新
  if (isSettingEditData.value) {
    return;
  }
  updateEndpointUrl();
});

// 更新完整的端点URL
const updateEndpointUrl = () => {
  const prefix = nodeForm.endpoint_type === 'unix_socket' ? 'unix://' : 'tcp://';
  nodeForm.endpoint_url = prefix + endpointPath.value;
};

// 从完整URL中提取路径部分
const extractPathFromUrl = (url) => {
  if (!url) return '';
  
  if (url.startsWith('unix://')) {
    return url.substring(7); // 移除 'unix://' 前缀
  } else if (url.startsWith('tcp://')) {
    return url.substring(6); // 移除 'tcp://' 前缀
  }
  
  return url;
};

// 表单验证规则
const rules = {
  name: [
    {
      required: true,
      message: t.value('nameRequired'),
      trigger: ['blur', 'change']
    },
    {
      min: 1,
      max: 50,
      message: t.value('nameLengthLimit'),
      trigger: ['blur', 'change']
    }
  ],
  identifier: [
    {
      max: 100,
      message: '节点标识长度不能超过100个字符',
      trigger: ['blur', 'change']
    }
  ],
  compose_path: [
    {
      max: 500,
      message: t.value('composePathLengthLimit') || 'Docker Compose路径长度不能超过500个字符',
      trigger: ['blur', 'change']
    }
  ],
  endpoint_url: [
    {
      required: true,
      message: t.value('endpointRequired'),
      trigger: ['blur', 'change']
    }
  ],
  tls_cert: [
    {
      required: () => nodeForm.endpoint_type === 'tcp' && nodeForm.use_tls,
      message: t.value('certRequired'),
      trigger: ['blur', 'change']
    }
  ],
  tls_key: [
    {
      required: () => nodeForm.endpoint_type === 'tcp' && nodeForm.use_tls,
      message: t.value('keyRequired'),
      trigger: ['blur', 'change']
    }
  ],
  tls_ca_cert: [
    {
      required: () => nodeForm.endpoint_type === 'tcp' && nodeForm.use_tls,
      message: t.value('caCertRequired'),
      trigger: ['blur', 'change']
    }
  ]
};

// 重置表单
const resetForm = () => {
  nodeForm.name = '';
  nodeForm.description = '';
  nodeForm.identifier = '';
  nodeForm.endpoint_type = 'unix_socket';
  nodeForm.endpoint_url = 'unix:///var/run/docker.sock';
  nodeForm.compose_path = '';
  nodeForm.use_tls = false;
  nodeForm.tls_cert = '';
  nodeForm.tls_key = '';
  nodeForm.tls_ca_cert = '';
  editingNodeId.value = null;
  endpointPath.value = '/var/run/docker.sock';
  // 移除对不存在的reset方法的调用
  // Arco Design的a-form组件不提供reset()方法，已通过手动重置表单字段完成
};

// 打开创建抽屉
const openCreateDrawer = () => {
  resetForm();
  isEditMode.value = false;
  drawerVisible.value = true;
};

// 打开编辑抽屉
const openEditDrawer = async (record) => {
  resetForm();
  isEditMode.value = true;
  editingNodeId.value = record.id;
  
  // 设置标志，防止watch监听器干扰
  isSettingEditData.value = true;
  
  // 填充表单数据
  nodeForm.name = record.name || '';
  nodeForm.description = record.description || '';
  nodeForm.identifier = record.identifier || '';
  nodeForm.compose_path = record.compose_path || '';
  nodeForm.endpoint_type = record.endpoint_type || 'unix_socket';
  
  // 保存原始的 endpoint_url
  const originalEndpointUrl = record.endpoint_url || '';
  nodeForm.endpoint_url = originalEndpointUrl;
  
  // 从记录中直接提取TLS配置（从顶级字段）
  nodeForm.use_tls = record.use_tls || false;
  // 将后端的client_cert映射到前端的tls_cert
  nodeForm.tls_cert = record.client_cert || '';
  // 将后端的client_key映射到前端的tls_key
  nodeForm.tls_key = record.client_key || '';
  // 将后端的ca_cert映射到前端的tls_ca_cert
  nodeForm.tls_ca_cert = record.ca_cert || '';
  
  // 添加调试日志，查看读取的数据
  console.log('编辑模式下读取的TLS配置:', {
    use_tls: nodeForm.use_tls,
    tls_cert: nodeForm.tls_cert,
    tls_key: nodeForm.tls_key,
    tls_ca_cert: nodeForm.tls_ca_cert
  });
  
  // 等待 Vue 更新周期完成后再设置端点路径
  await nextTick();
  
  // 提取端点路径（去掉协议前缀）
  endpointPath.value = extractPathFromUrl(originalEndpointUrl);
  
  // 重置标志
  isSettingEditData.value = false;
  
  drawerVisible.value = true;
};

// 关闭抽屉
const closeDrawer = () => {
  drawerVisible.value = false;
};

// 提交表单
const handleSubmit = async () => {
  try {
    // 验证表单
    if (nodeFormRef.value) {
      const validateResult = await nodeFormRef.value.validate();
      if (validateResult) {
        // 验证失败，不继续提交
        return;
      }
    }
    
    submitting.value = true;
    
    // 构建请求数据 - 根据后端实际数据结构调整
    const formData = {
      name: nodeForm.name,
      description: nodeForm.description,
      identifier: nodeForm.identifier,
      endpoint_type: nodeForm.endpoint_type,
      endpoint_url: nodeForm.endpoint_url,
      compose_path: nodeForm.compose_path,
      use_tls: nodeForm.endpoint_type === 'tcp' ? nodeForm.use_tls : false,
      client_cert: nodeForm.endpoint_type === 'tcp' ? nodeForm.tls_cert : '',
      client_key: nodeForm.endpoint_type === 'tcp' ? nodeForm.tls_key : '',
      ca_cert: nodeForm.endpoint_type === 'tcp' ? nodeForm.tls_ca_cert : '',
      connection_config: {
        base_url: nodeForm.endpoint_url
      }
    };
    
    // 添加调试日志，查看提交的数据
    console.log('提交的表单数据:', JSON.stringify(formData, null, 2));
    
    if (isEditMode.value && editingNodeId.value) {
      // 更新节点
      await updateContainerNode(editingNodeId.value, formData);
      Message.success(t.value('updateSuccess'));
    } else {
      // 创建节点
      await createContainerNode(formData);
      Message.success(t.value('createSuccess'));
    }
    
    // 关闭抽屉
    closeDrawer();
    
    // 重新加载节点列表
    fetchContainerNodes(pagination.current);
    
  } catch (error) {
    console.error('提交表单失败:', error);
    Message.error(error.message || t.value('operationFailed'));
  } finally {
    submitting.value = false;
  }
};

// 处理文件上传
const handleFileUpload = (fieldName) => {
  const input = document.createElement('input');
  input.type = 'file';
  input.accept = '.pem,.crt,.key,.cert';
  
  input.onchange = (event) => {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (e) => {
        const content = e.target.result;
        nodeForm[fieldName] = content;
        Message.success(t.value('fileUploadSuccess'));
      };
      reader.onerror = () => {
        Message.error(t.value('fileUploadFailed'));
      };
      reader.readAsText(file);
    }
  };
  
  input.click();
};

// 显示删除确认对话框
const showDeleteModal = (record) => {
  // 前端添加删除限制：当identifier为localhost时不允许删除
  if (record.identifier === 'localhost') {
    Message.warning(t.value('cannotDeleteLocalhostNode'));
    return;
  }
  nodeToDelete.value = record;
  deleteModalVisible.value = true;
};

// 取消删除
const cancelDelete = () => {
  deleteModalVisible.value = false;
  nodeToDelete.value = null;
};

// 确认删除
const confirmDelete = async () => {
  if (!nodeToDelete.value) {
    cancelDelete();
    return;
  }
  
  // 再次确认，防止绕过前端限制
  if (nodeToDelete.value.identifier === 'localhost') {
    Message.warning(t.value('cannotDeleteLocalhostNode'));
    cancelDelete();
    return;
  }
  
  try {
    await deleteContainerNode(nodeToDelete.value.id);
    Message.success(t.value('deleteSuccess'));
    
    // 重新加载节点列表
    fetchContainerNodes(pagination.current);
  } catch (error) {
    console.error('删除节点失败:', error);
    // 如果是因为权限错误（后端限制），显示更具体的错误信息
    if (error.response && error.response.status === 403) {
      Message.error(t.value('cannotDeleteLocalhostNode'));
    } else {
      Message.error(error.message || t.value('operationFailed'));
    }
  } finally {
    cancelDelete();
  }
};

// 删除节点 - 兼容旧调用方式（如果有其他地方调用）
const handleDelete = async (nodeId) => {
  // 查找节点记录
  const record = containerNodes.value.find(node => node.id === nodeId);
  if (record) {
    showDeleteModal(record);
  }
};

// 组件挂载时获取节点列表
onMounted(() => {
  fetchContainerNodes();
  
  // 初始化检测是否为移动设备
  checkIsMobile();
  // 添加窗口大小变化监听
  window.addEventListener('resize', checkIsMobile);
  
  // 设置定时器，每分钟刷新一次节点状态
  const statusInterval = setInterval(refreshNodeStatuses, 60000);
  
  // 组件卸载时清除定时器和事件监听
  onUnmounted(() => {
    clearInterval(statusInterval);
    window.removeEventListener('resize', checkIsMobile);
  });
});
</script>

<style scoped>
.containers-container {
  padding: 20px;
}

.card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 15px;
  font-size: 1.3em;
  padding: 20px 20px;
  border-bottom: 1px solid rgba(0, 0, 0, 0.1);
}

.title {
  margin: 0;
  padding: 0;
}

/* 添加按钮容器样式 */
.header-actions {
  margin-left: auto;
}

.desc {
  margin-top: 4px;
  color: #8c8c8c;
  font-size: 12px;
}

/* 表单样式 */
.arco-form-item {
  margin-bottom: 20px;
}

/* 表单提示样式 */
.form-hint {
  margin-top: 8px;
}

.hint-text {
  color: var(--color-warning-5);
  font-size: 12px;
}

/* 端点前缀样式 - 跟随主题变化 */
.endpoint-prefix {
  background-color: var(--color-fill-2) !important;
  color: var(--color-text-2) !important;
  font-weight: 500 !important;
  text-align: center !important;
  border-right: none !important;
}

.endpoint-prefix .arco-input {
  background-color: var(--color-fill-2) !important;
  color: var(--color-text-2) !important;
  font-weight: 500 !important;
  text-align: center !important;
  cursor: default !important;
}

/* 暗色主题适配 */
[arco-theme='dark'] .endpoint-prefix {
  background-color: var(--color-fill-3) !important;
  color: var(--color-text-1) !important;
}

[arco-theme='dark'] .endpoint-prefix .arco-input {
  background-color: var(--color-fill-3) !important;
  color: var(--color-text-1) !important;
}

/* TLS 证书容器 - 强制垂直布局 */
.cert-container {
  display: flex;
  flex-direction: column;
  width: 100%;
}

/* TLS 证书文本框样式 */
.cert-textarea {
  font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace !important;
  font-size: 12px !important;
  line-height: 1.4 !important;
  width: 100%;
  margin-bottom: 8px;
}

.cert-actions {
  display: flex;
  gap: 8px;
  justify-content: flex-end;
  width: 100%;
}

/* 响应式调整 */
@media (max-width: 768px) {
  .containers-container {
    padding: 10px;
  }
  
  .card-header {
    font-size: 1.1em;
    padding: 15px 15px;
    flex-direction: column;
    align-items: flex-start;
    gap: 10px;
  }
}
</style>