user tengine;
worker_processes auto;
error_log /opt/blackpotbp/tengine/logs/error.log;
pid /opt/blackpotbp/tengine/logs/nginx.pid;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /opt/blackpotbp/tengine/logs/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /opt/blackpotbp/tengine/conf/mime.types;
    default_type        application/octet-stream;

    # HTTPS服务
  server {
        listen 11443 ssl;
        server_name  127.0.0.1;

        # SSL证书配置
        ssl_certificate "/opt/blackpotbp/app/ssl/bp.crt";
        ssl_certificate_key "/opt/blackpotbp/app/ssl/bp.key";
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        location / {
            root /opt/blackpotbp/tengine/html/dist;
            try_files $uri $uri/ /index.html;
        }

        # 后端API代理
        location /demo/v1/api/ {
            proxy_pass http://localhost:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # WebSocket代理
        location /ws/ {
            proxy_pass http://localhost:5000/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
       
    }

}

