# 应用配置
APP_NAME=BlackPotBPanel
DEBUG=False
VERSION=0.0.2

# JWT配置
SECRET_KEY=your-secret-key-change-in-production
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=1440

# 时区配置
TIMEZONE=Asia/Shanghai

# API文档配置
# 设置为False可禁用Swagger UI和ReDoc文档页面
ENABLE_DOCS=True

# 通用设置
LANGUAGE=zh-CN
THEME=dark
# 登录通知
LOGIN_NOTIFY=True
# 回收站配置
RECYCLE=True

# 服务器配置
HOST=0.0.0.0
PORT=8000

DEMO_MODE=False

# SSL配置
SSL_ENABLED=True
SSL_CERT_PATH=./data/ssl/ssl.crt
SSL_KEY_PATH=./data/ssl/ssl.key
    
