# 错误页面物理路径定义
# 使用 internal 确保外部无法直接通过 URL 访问这些 HTML 文件
location = /400.html {
    internal;
    root /usr/local/openresty/nginx/waf_html;
    add_header Cache-Control "no-cache";
}

location = /404.html {
    internal;
    root /usr/local/openresty/nginx/waf_html;
}

location = /500.html {
    internal;
    root /usr/local/openresty/nginx/waf_html;
}

location = /502.html {
    internal;
    root /usr/local/openresty/nginx/waf_html;
}

location = /503.html {
    internal;
    root /usr/local/openresty/nginx/waf_html;
}

location = /504.html {
    internal;
    root /usr/local/openresty/nginx/waf_html;
}