    set $waf_mode "record";
    set $cc_enabled 1;
    set $bot_enabled 1;
    set $bot_verify_enabled 1;
    set $scanner_enabled 1;
    set $blackwhite_enabled 1;
    set $sql_enabled 1;
    set $xss_enabled 1;
    set $ssrf_enabled 1;
    set $cmd_injection_enabled 1;
    set $csrf_enabled 1;
    set $file_inclusion_enabled 1;
    set $file_upload_enabled 1;
    set $ldap_injection_enabled 1;
